version: '3'
services:
  marketplace:
    image: robsontenorio/laravel
    environment:
      DATABASE_CLIENT: mkt_db
      DATABASE_NAME: mkt_db
      DATABASE_HOST: mkt_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: mkt_db
      DATABASE_PASSWORD: mkt_db
    links:
      - mkt_db:mkt_db
    volumes:
      - ../:/var/www/app:cached
    ports:
      - 8080:8080
    depends_on: 
      - mkt_db

  mkt_db:
    image: postgres
    environment:
      POSTGRES_USER: mkt_db
      POSTGRES_PASSWORD: mkt_db
    ports:
      - '5432:5432'
